<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-EK0HI42" ignored="0" name="Validate Test" tests="2" failures="2" timestamp="19 Nov 2021 18:04:33 GMT" time="100.14" errors="0">
  <testcase name="basepageNavigation" time="0.069" classname="SandipFoundation.EndtoendPRoject.validateTitle">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;...123&amp;gt; but was:&amp;lt;...&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<...123> but was:<...>
at junit.framework.Assert.assertEquals(Assert.java:81)
at junit.framework.Assert.assertEquals(Assert.java:87)
at SandipFoundation.EndtoendPRoject.validateTitle.basepageNavigation(validateTitle.java:29)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- basepageNavigation -->
  <testcase name="basepageNavigation" time="0.078" classname="SandipFoundation.EndtoendPRoject.validateTitle">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Resources.base.getscreenShot(base.java:52)
at SandipFoundation.EndtoendPRoject.Listenrs.onTestFailure(Listenrs.java:40)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- basepageNavigation -->
</testsuite> <!-- Validate Test -->
